### ISSUE TITLE
Enhancement Request

### ISSUE THREAD

**Issue by Raytri3** [chrismaddalena/Goreport#10]
When processing a report for multiple campaigns we get the "warning" that this may take some time; however it looked like it was processing very fast until about half way then it looked like it hung for a while and then continued fast again. When it paused it looked like the whole program hung/crashed but after a few minutes it continued on. - It would be nice to have more on-screen reporting so we know it isn't crashed.

**Comment by jordan-wright** [comment]
Was there a particular campaign that stood out? Like, is there one campaign that's much bigger than the rest of them?

**Comment by Raytri3** [comment]
No not really (4 campaigns of 17,22,22,22 for a total of 83 folks). I did
some digging and think I know why it slowed down (really just sat at one
for about 10 minutes) - one user had some weird results. They "clicked" 77
times with 77 different browsers - this of course isn't right so I suspect
they reported the phishing site to Google/Windows and they in turn visited
the link (and if it had the users identifier it would appear to have
originated from that user). I think it was this user that slowed down the
results. It would have been nice to see something like .....  or something
across the screen as we waited just so we know the program isn't hung.
Again a simple nice to have - doesn't really matter as far as functionality
goes.

Ray

**Comment by chrismaddalena** [comment]
Thanks for the suggestion, Ray. I can look into this and see what I might be able to do for these cases. This sort of thing is why I have GoReport provide a progress report of sorts ("working on x/1209"), but you're right, it doesn't keep updating or providing feedback until it finishes that piece. I think I have something in another tool of mine I may be able to repurpose for a sort of progress bar.

You are right, though. GoReport can move very quickly through report composition when its just assembling tables, but you'll see the results slow down when GoReport has to parse a large number of results for a single recipient. I have seen cases like you described. When I have seen those sorts of results, it was as you suggested. The recipient submitted the GoPhish link to urlquery or VirusTotal, which triggers "clicks" from either several Mountain View, CA servers owned by Google or some servers in Norway.

Then you can start seeing all kinds of wild results, like clicks from Russia, China, the UK, and elsewhere, presumably from people reviewing the latest submissions to these services. Each new IP means another geo IP lookup, another row in a table, etc. GoReport has to give some of the APIs and web services a second between requests, so time start to add up quickly.

**Comment by chrismaddalena** [comment]
Closing this out because these issues have been addressed in the latest release. Geolocate requests are far more efficient now. There's also much, much more included in v3.0 just pushed to master.
