### ISSUE TITLE
Python Lib Missing, But they aren't

### ISSUE THREAD

**Issue by turnerdb** [chrismaddalena/GoReport#13]
cli output:
[device@device.owner]# python GoReport.py --id 189 --format quick
[!] Could not import the GoPhish library! Make sure it is installed.
Run: `python3 -m pip intall gophish`
Test it by running `python3` and then, in the Python prompt, typing `from gophish import Gophish`.

GoPhish library is installed.  Verified by running the pip -r install requirements.txt again.  Seemed to work fine last time I used it.  Only change is that I have patched the system it is on.  Are there any known issue with the latest CentOS patches and the application.  I don't run it at python3 just python....is that possible an issue now?

Thanks.

**Comment by turnerdb** [comment]
This is where everything was installed:
Requirement already satisfied: python-docx in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: maxminddb-geolite2 in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: requests in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: gophish in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: configparser in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: python-dateutil in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: user-agents in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: click in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: lxml>=2.3.2 in /usr/lib64/python2.7/site-packages (from python-docx->-r requirements.txt (line 1))
Requirement already satisfied: maxminddb in /usr/lib/python2.7/site-packages (from maxminddb-geolite2->-r requirements.txt (line 2))
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 3))
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 3))
Requirement already satisfied: idna<2.7,>=2.5 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 3))
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/lib/python2.7/site-packages (from requests->-r requirements.txt (line 3))
Requirement already satisfied: six>=1.5 in /usr/lib/python2.7/site-packages (from python-dateutil->-r requirements.txt (line 6))
Requirement already satisfied: ua-parser>=0.4.1 in /usr/lib/python2.7/site-packages (from user-agents->-r requirements.txt (line 7))
Requirement already satisfied: ipaddress in /usr/lib/python2.7/site-packages (from maxminddb->maxminddb-geolite2->-r requirements.txt (line 2))

**Comment by turnerdb** [comment]
Just redid the install and setup using python3.  Works fine just needed to learn how to install pip3 so that the lib would map to python3 instead.  I guessing on of the patches broke the relationship and ability to use python which is what I did before.

**Comment by chrismaddalena** [comment]
I have been traveling this week, so I missed this until now. I'm glad you found the solution and appreciate the update! Let me know if you run into any other issues.
