### ISSUE TITLE
--complete skips the last campaign

### ISSUE THREAD

**Issue by expectmore-commscope** [chrismaddalena/Goreport#15]
Hi Chris,

I noticed that when using the --complete flag, Go report skips setting the last campaign in the list to complete and proceeds to generate the report. In this case campaign ID 25 does not get set to complete before the report starts getting generated.

![image](https://user-images.githubusercontent.com/23272419/40577400-7dcdd7aa-6137-11e8-81d9-519f2ed37efd.png)

**Comment by chrismaddalena** [comment]
Sorry for the delayed response. I'm looking into this. Thanks for letting me know! I expect it should be a simple fix.

**Comment by chrismaddalena** [comment]
Sorry this took _forever_ to get done, but life happens. This fix and much, much more is included in v3.0 just pushed to master.
