### ISSUE TITLE
Add report from version 0.6 to docx report

### ISSUE THREAD

**Issue by oded86w** [chrismaddalena/Goreport#16]
Hi 
You can add the reports statistic to reports  ? 
it's new feature in version 0.6

**Comment by chrismaddalena** [comment]
Yes, that could be done, if there is an API endpoint for it. What specific statistics are you looking for? I have used 0.6, but am unaware of any new statistics. I know there's now a "Reported" category for campaigns, but have no worked with it myself.

**Comment by chrismaddalena** [comment]
Got it. I will see what I can do. It should be easy to add the "reported" events. I saw that new data in GoPhish, but have not seen the reporting functionality used myself. 

Looking into this now to see if I can simulate the event and figure out how it is recorded.

**Comment by Cycl0pe** [comment]
Hello @chrismaddalena, can we have an update on this feature so far?

Thanks a lot and great project!

Cycl0pe

**Comment by chrismaddalena** [comment]
@Cycl0pe I'll be working on this sometime this week. I'm going to setup a test database using the latest GoPhish and do a lot of rewriting to update GoReport and fix some issues, including adding support for the "reported email" metric. I've been traveling nearly non-stop for a while and just haven't had time to work on GoReport.

**Comment by chrismaddalena** [comment]
Quick update: I will be using the recently added demo instance to add new features, like this one. Should be done soon.

**Comment by chrismaddalena** [comment]
Sorry this took _forever_ to get done, but life happens. This and much, much more is included in v3.0 just pushed to master.
