### ISSUE TITLE
Error creating report

### ISSUE THREAD

**Issue by CyberM070** [chrismaddalena/Goreport#23]
Traceback (most recent call last):
  File "GoReport.py", line 20, in <module>
    from lib import banners, goreport
  File "/opt/gophish/goreport/lib/goreport.py", line 19, in <module>
    from user_agents import parse
ModuleNotFoundError: No module named 'user_agents'

All requirements have been installed, any idea how to fix this? 

Thanks in advance

**Comment by bsmithday** [comment]
Not sure why, but it seems to be an error loading the 'user_agents' module when using python3. In my case, the report is generated using my default python installation:
E.g.,
python GoReport.py --id 18 --format excel --config Gophish.config

**Comment by CyberM070** [comment]
Worked like a charm!
