### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by MrGoldenpioche** [chrismaddalena/Goreport#24]
Hello. When I trying to generate report with format xlsx or docx, I have the following error at the end. 

**[+] Processed detailed analysis for 1040 of 1040.
[+] Finished writing detailed analysis...
[!] There was a problem processing campaign ID 14!
L.. Details: [Errno 2] No such file or directory: 'Gophish Results for Extend mailbox capacity / group 1.xlsx'`**

When I try to do it with --format quick, all is working. Maybe an issue in the generation of the output files ? does your script support special char like slash ( / ) ?

**Comment by gremaudc** [comment]
I confirm that the problem is because I using a Slash ( / ) in my campaign. 
You should parse the campaign name in your function get_basic_campaign_info to remove special char like the ( / )

` self.cam_name = self.campaign.name`

**Comment by DKhalaf** [comment]
I've done what you did but still have the same problem. Any suggestions?

**Comment by gremaudc** [comment]
> I've done what you did but still have the same problem. Any suggestions?

hello @DKhalaf , maybe you can try to print out the value of the self.cam_name before using my trick and try to print out after using my command to see the difference. What campaign name do you have ?

Best regards.

**Comment by DKhalaf** [comment]
So I didn't have any "/" in my campaign names. But after I saw your thread I tried with a "/" but had no luck with that. Idk, I guess I'll just move on and forget about this tool. Not sure if I want to spend my time trying to fix something that might not work optimal. Its for a project and we're in a hurry :-)

**Comment by chrismaddalena** [comment]
If you are using macOS the latest version will not allow Python to access your folder, so it can't find the file. You'll need to `sudo` the command or figure out how to grant the permissions.
