### ISSUE TITLE
Error with campaign ID when generating report

### ISSUE THREAD

**Issue by DKhalaf** [chrismaddalena/Goreport#25]
> [+] A total of 1 campaign IDs have been provided for processing.
> [+] GoReport will process the following campaign IDs: 88
> [+] Now fetching results for Campaign ID 88 (1/1).
> [!] There was a problem fetching this campaign ID's details. Make sure your URL and API key are correct. Check HTTP vs HTTPS!
> L.. Details: super() takes at least 1 argument (0 given)
> [+] Success!
> [!] Looks like campaign ID None does not exist! Skipping it...
> [!] There was a problem processing campaign ID 88!
> L.. Details: 'NoneType' object has no attribute 'timeline'

Any suggestions on how to fix this?
btw, both url and id are correct and im running http.

**Comment by CyberM070** [comment]
Hi Chris,

I experience the same issue here, please help to fix this.

**Comment by PrashantSharma-26** [comment]
Hey Chris,

Getting the same issue, please help!

**Comment by SarthakKohli** [comment]
Facing same issue , kindly guide to resolve 
Thanks

**Comment by CyberM070** [comment]
I am using version 0.9.0. I even tried to copy the database to the older version op Gophish, where Goreport used to work in the past, and that didn't work as well. Perhaps it has something to do with campaigns that have been conducted via the latest version?

**Comment by ahmedkhlief** [comment]
Solved the issue by : 

python3 -m pip install --upgrade urllib3

**Comment by ahmedkhlief** [comment]
I traced the issue to error : 
urllib3.exceptions.LocationParseError: Failed to parse: https://<url>:3333/api/campaigns/

the solution was : 

python3 -m pip install --upgrade urllib3

**Comment by CyberM070** [comment]
> I traced the issue to error :
> urllib3.exceptions.LocationParseError: Failed to parse: https://:3333/api/campaigns/
> 
> the solution was :
> 
> python3 -m pip install --upgrade urllib3

Thanks for the suggestion but it did not work for me. Hope that @chrismaddalena can fix this issue.

**Comment by dineshdinz** [comment]
I am also facing the same issue. 

[+] A total of 1 campaign IDs have been provided for processing.
[+] GoReport will process the following campaign IDs: 5
[+] Now fetching results for Campaign ID 5 (1/1).
[!] There was a problem fetching this campaign ID's details. Make sure your URL and API key are correct. Check HTTP vs HTTPS!
L.. Details: Failed to parse: https://:3333/api/campaigns/5
[+] Success!
[!] Looks like campaign ID None does not exist! Skipping it...
[!] There was a problem processing campaign ID 5!
L.. Details: 'NoneType' object has no attribute 'timeline'

**Comment by vincentcox** [comment]
I think the tool is broken...

**Comment by vincentcox** [comment]
Okay, so I did some debugging.
The error is triggered here: https://github.com/chrismaddalena/Goreport/blob/master/lib/goreport.py#L433

**Comment by kpomeroy1979** [comment]
I also ran into a similar issue a while ago and my fix was to DISABLE my
iptables firewall. Once I disabled the firewall, the GoReport script ran
and generated reports as expected.

Hope this helps someone.

Cheers

**Comment by vincentcox** [comment]
@kpomeroy1979, did you ran it over HTTP instead of HTTPS? I am digging in the code and I think there is something about that.

**Comment by vincentcox** [comment]
@kpomeroy1979 , just tested, it has no effect... I have no idea why it's failing

**Comment by vincentcox** [comment]
I followed the trace and I ended up at: https://github.com/chrismaddalena/Goreport/blob/master/lib/goreport.py#L230
This is where the error occurs

**Comment by vincentcox** [comment]
Okay I found the fix!

```
git clone git://github.com/urllib3/urllib3.git
python setup.py install
```

Have a [nice weekend](https://www.youtube.com/watch?v=IwLSrNu1ppI) guys!

**Comment by kpomeroy1979** [comment]
I ran it over HTTPS.

Have you ever been able to successfully run a report?
Also make sure your permissions are right on the directories (just a shot
in the dark).
Check your goreport/gophish.conf and make sure your gp_host is correct. It
should be https://x.x.x.x:3333/ and that your API key is correct.

Also, when I had my firewall ENABLED and was getting errors, I saw this in
the output and fixed it like so. There was also another reference to an ot
of date python utility but I can't remember now off the top of my head
which one it was.

ERROR: gophish 0.4.0 has requirement python-dateutil==2.6.0, but you'll
have python-dateutil 2.8.1 which is incompatible.

# pip uninstall python-dateutil

# apt-get remove --auto-remove python-dateutil

# apt-get purge --auto-remove python-dateutil

# pip install python-dateutil==2.6.0

**Comment by kpomeroy1979** [comment]
That was the other one I had to fix, urllib3.

good job.
