### ISSUE TITLE
(SOLVED) There was a problem reading values from the gophish.config file!

### ISSUE THREAD

**Issue by gkaman94** [chrismaddalena/Goreport#29]
Hello Everyone,

Hope you all have a great day. 

I'v installed GoReport on the Host where GoPhish is running.

I have followed the instructions by creating a config file in the GoReport and GoPhish main directory 

But i receive an error from GoReport.

 There was a problem reading values from the gophish.config file!
L.. Details: No section: 'Gophish'

At this point i'm stuck, unfortunatelly i'm new with the API stuff never done this before.

Please let me know what i'm missing or what is the exact task when creating the config file (location,permission,etc..)

Any help is much appreciated, thank you in advance.

Input from the config file:

from gophish import Gophish

 api_key = 'API_KEY'
 api = Gophish(XXXXXXX8997f2219ad6b73b03dd64b4XXXXXXXe5cb54179241fe501a542XXXXX; host='https://X.0.0.X:33XX')

**Comment by kpomeroy1979** [comment]
Hello,

Here is a copy of my gophish.config file that works with GoReport. Make
sure your config file is formatted correctly.

[Gophish]
gp_host: https://XXXXXX.com:65333
api_key: 86e337cb2fc5XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

[ipinfo.io]
ipinfo_token: f25XXXXXXXXXXXX

[Google]
geolocate_key: AIzaSyDtUXXXXXXXXXXXXXXXX

Also, make sure GoReport has permissions to read the file and the directory
*# chmod 644 gophish.config*

[image: image.png]

[image: image.png]

**Comment by gkaman94** [comment]
@kpomeroy1979 Thank you kindly for the reply.

To summarise i need to create the .conf file in the GoReport main directory and use chmod 644 on the file so it can read from it? 

Thank you in advance.

**Comment by gkaman94** [comment]
Thank you for the suggestion. The GoReport module is now working as expected.

@kpomeroy1979 you are awesome

**Comment by chrismaddalena** [comment]
Glad the problem is resolved, @gkaman94! Thanks for updating the ticket.

And thank you for helping then, @kpomeroy1979!
