### ISSUE TITLE
pip3 required to install requirements

### ISSUE THREAD

**Issue by ismailyenigul** [chrismaddalena/GoReport#3]
Hi,

On many linux disto default pip works for python 2.X. 
Goreports requires python3 and pip3 must be installed to install correct modules for python3

On ubuntu, the following commands needs to be executed.

sudo apt-get install python3-pip
pip3 install -r requirements.txt

Thanks

**Comment by chrismaddalena** [comment]
Yes, that is correct. GoReport is written in Python 3 and uses Python 3 libraries. I can add this to the README to call it out.

Thanks for the feedback! I'm going to close the issue, but I'll add some info to the README for this.

**Comment by bsmithday** [comment]
Please edit the README. Thanks
