### ISSUE TITLE
Can We Track Passwords Entered on a Phishing Landing Page Through Go-Report?

### ISSUE THREAD

**Issue by mrrobotnl** [chrismaddalena/Goreport#37]
I'm getting ready to use Go-Report for our phishing servers, but I have a question. Apart from the click results, is it also possible for us to access the passwords that users have entered on the landing page? Thanks in advance.

**Comment by kpomeroy1979** [comment]
Yes Go-Report will contain the credentials  entered. Sent from my iPhoneOn Oct 19, 2023, at 12:52 AM, mrrobotnl ***@***.***> wrote:﻿
I'm getting ready to use Go-Report for our phishing servers, but I have a question. Apart from the click results, is it also possible for us to access the passwords that users have entered on the landing page? Thanks in advance.
