### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by doomguy** [chrismaddalena/GoReport#6]
Hi there,

seems like there is a bug with encoding somewhere. All I get is the error below. From what I know, there are no unicode characters in the source.

Any ideas on how to solve this?

Thanks!

> [+] Connecting to GoPhish at https://10.XXX.XXX.XXX:3333
L.. The API Authorization endpoint is: https://10.XXX.XXX.XXX:3333/api/campaigns/?api_key=XXX
[+] A total of 1 campaign IDs have been provided for processing.
[+] GoReport will process IDs 3
()
[+] Now fetching results for Campaign ID 3 (1/1).
[+] Success!
[+] Building the report -- you selected a csv report.
[!] There was a problem processing campaign ID 3!
L.. Details: 'ascii' codec can't encode characters in position 8-9: ordinal not in range(128)

**Comment by doomguy** [comment]
Seems like it was related to python2. Here is a small recipe to get GoReport running on kali with python3:

> apt install virtualenv
> virtualenv -p /usr/bin/python3 py3env
> source py3env/bin/activate
> pip install -r requirements.txt
> python3 GoReport.py --id 3 --format word

**Comment by chrismaddalena** [comment]
Hey there,

I'm glad to hear you figured it out. Thanks for updating the issue. You are right -- GoReport is written entirely in Python 3, so it is needed to run GoReport.

Let me know if there are any other issues.
