### ISSUE TITLE
Aggregating Reports

### ISSUE THREAD

**Issue by SiDoggyDog1** [chrismaddalena/GoReport#7]
Is it possible to or will it ever be possible to aggregate reports from different campaigns? I would like to run several campaigns but compile all of the data into one report.

**Comment by chrismaddalena** [comment]
It is currently possible to do this. If you split your phish into several GoPhish campaigns, you can then report on all of those campaigns at once -- and get one report -- using GoReport.

Just gather up all of your campaign IDs. Then use the `--combine` argument when running your reports. Something like this:

`python3 goreport.py --id 26,29-33,54 --format csv --combine`

That command will collect the results of campaigns 26, 29, 30, 31, 32, 33, and 54 and make one big report out of the results, as if they were all one GoPhish campaign. You'll get one report document with everything combined. Without `--combine` you'll get separate reports for each campaign.

Does that answer your question?
